## LA Parking Citation Exploratory Data Analysis

#### Fisher Ankney
#### October 27th, 2018

<br> 

data avaliable on Kaggle or https://data.lacity.org/

This goal of this notebook is to trim the dataset from 7.2 million lines, to a more manageable size, specifically one that can be stored on github (< 100 mb files)

### Load Libraries

In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Verify File Size

In [70]:
# return file size in GB
import os
os.path.getsize('parking_citation.csv') / (1*10**9)

1.021944555

### Read in the Dataset

In [71]:
la_ticket_full = pd.read_csv("~/Documents/data_science/py_la_tickets/parking_citation.csv")

/Applications/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [72]:
la_ticket_full.tail()

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
7201001,4334262026,2018/05/29 12:00:00 AM,2321.0,NaN,NaN,CA,200608.0,NaN,HOND,PA,GY,9400 HAAS AVE,00531,55.0,80.56E4+,RED ZONE,93.0,6.465617e+06,1.804786e+06
7201002,4334262030,2018/05/29 12:00:00 AM,2322.0,NaN,NaN,CA,200608.0,NaN,HOND,PA,GY,9400 HAAS AVE,00531,55.0,5204A-,DISPLAY OF TABS,25.0,6.465617e+06,1.804786e+06
7201003,4334262041,2018/05/29 12:00:00 AM,2338.0,NaN,NaN,CA,201811.0,NaN,BMW,PA,GY,7500 BUDLONG AVE,00531,55.0,80.56E4+,RED ZONE,93.0,6.471860e+06,1.812272e+06
7201004,4334262052,2018/05/29 12:00:00 AM,2341.0,NaN,NaN,CA,201809.0,NaN,CHEV,PA,GY,944 76TH ST W,00531,55.0,22514,FIRE HYDRANT,68.0,6.473632e+06,1.811856e+06
7201005,4334262063,2018/05/29 12:00:00 AM,2348.0,NaN,NaN,CA,201810.0,NaN,HOND,PA,GY,618 76TH ST W,00531,55.0,22500E,BLOCKING DRIVEWAY,68.0,6.475427e+06,1.811860e+06

### Index Dataset for 2017 Results Only

In [73]:
la_ticket_issue = la_ticket_full['Issue Date']
la_ticket_issue.tail()

7201001    2018/05/29 12:00:00 AM
7201002    2018/05/29 12:00:00 AM
7201003    2018/05/29 12:00:00 AM
7201004    2018/05/29 12:00:00 AM
7201005    2018/05/29 12:00:00 AM
Name: Issue Date, dtype: object

In [74]:
type(la_ticket_issue)

pandas.core.series.Series

In [75]:
sum(la_ticket_issue.str.contains('2017') == True)

2254329

In [76]:
la_ticket_2017_index = la_ticket_issue.str.contains('2017')

In [77]:
la_ticket_2017 = la_ticket_full[la_ticket_2017_index]

In [78]:
len(la_ticket_2017)

2254329

#### Confirm Dataset Retains Essential Variables and spans 2017

In [79]:
la_ticket_2017.tail()

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
7094534,1116259045,2017/04/17 12:00:00 AM,2008.0,NaN,NaN,NV,201812.0,NaN,CHRY,PA,GY,2800 EAST OBSERVATOR,NaN,4.0,8056E4,RED ZONE,93.0,9.999900e+04,9.999900e+04
7133441,1116014793,2017/11/05 12:00:00 AM,150.0,NaN,NaN,CA,201709.0,NaN,ACUR,PA,GY,BURNS E/O VIRGIL,NaN,1.0,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04
7171053,1114199203,2017/10/15 12:00:00 AM,1637.0,NaN,NaN,CA,201801.0,NaN,HOND,PA,BK,2167 E 102ND ST,01829,1.0,80714,PRIVATE PROPERTY,68.0,6.490781e+06,1.802058e+06
7171388,1121068082,2017/04/16 12:00:00 AM,735.0,NaN,NaN,CA,201706.0,NaN,CHEV,PA,BL,6701 DE SOTO AVE,MQ,1.0,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04
7171390,1122798622,2017/03/05 12:00:00 AM,1635.0,NaN,NaN,CA,201805.0,NaN,TOYO,PA,GY,101 WORLD WAY,5M38,2.0,225078A,HANDICAP/NO DP ID,363.0,6.439738e+06,1.802687e+06

In [80]:
min(la_ticket_2017['Issue Date'])

'2017/01/01 12:00:00 AM'

In [81]:
max(la_ticket_2017['Issue Date'])

'2017/12/31 12:00:00 AM'

### Remove 'Useless' Variables

In [82]:
la_ticket_2017 = la_ticket_2017.drop(['Ticket number', 'VIN', 'Marked Time', 'Plate Expiry Date', 'Route', 'Agency'], axis=1)

In [83]:
la_ticket_2017.head()

,Issue Date,Issue time,Meter Id,RP State Plate,Make,Body Style,Color,Location,Violation code,Violation Description,Fine amount,Latitude,Longitude
2735704,2017/12/18 12:00:00 AM,2205.0,NaN,CA,HOND,PA,BK,1323 S FLOWER ST,4000A1,NO EVIDENCE OF REG,50.0,6.480729e+06,1.836883e+06
2771883,2017/05/11 12:00:00 AM,800.0,NaN,CA,FRHT,TR,WH,INDIANA/NOAKES,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04
2777524,2017/03/01 12:00:00 AM,104.0,NaN,OR,TOYT,PA,BL,1822 WINONA BLVD,80.56E4+,RED ZONE,93.0,6.470239e+06,1.860397e+06
2777558,2017/03/28 12:00:00 AM,1050.0,NaN,CA,HOND,PA,BK,710 EL CENTRO AV,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04
2777651,2017/05/15 12:00:00 AM,134.0,NaN,CA,LEXS,PA,BL,1701 VINE ST,80.69B,NO PARKING,73.0,6.462770e+06,1.859525e+06

### Split Issue Date into Month / Day

In [84]:
date_split = la_ticket_2017['Issue Date'].str.split('/', n=3, expand=True)
date_split.head()
#new = data["Name"].str.split(" ", n = 1, expand = True)

            0   1               2
2735704  2017  12  18 12:00:00 AM
2771883  2017  05  11 12:00:00 AM
2777524  2017  03  01 12:00:00 AM
2777558  2017  03  28 12:00:00 AM
2777651  2017  05  15 12:00:00 AM

In [85]:
# making seperate first name column from new data frame 
la_ticket_2017["Month"]= date_split[1] 
la_ticket_2017['Split_2'] = date_split[2]

la_ticket_2017.head()

,Issue Date,Issue time,Meter Id,RP State Plate,Make,Body Style,Color,Location,Violation code,Violation Description,Fine amount,Latitude,Longitude,Month,Split_2
2735704,2017/12/18 12:00:00 AM,2205.0,NaN,CA,HOND,PA,BK,1323 S FLOWER ST,4000A1,NO EVIDENCE OF REG,50.0,6.480729e+06,1.836883e+06,12,18 12:00:00 AM
2771883,2017/05/11 12:00:00 AM,800.0,NaN,CA,FRHT,TR,WH,INDIANA/NOAKES,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,05,11 12:00:00 AM
2777524,2017/03/01 12:00:00 AM,104.0,NaN,OR,TOYT,PA,BL,1822 WINONA BLVD,80.56E4+,RED ZONE,93.0,6.470239e+06,1.860397e+06,03,01 12:00:00 AM
2777558,2017/03/28 12:00:00 AM,1050.0,NaN,CA,HOND,PA,BK,710 EL CENTRO AV,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,03,28 12:00:00 AM
2777651,2017/05/15 12:00:00 AM,134.0,NaN,CA,LEXS,PA,BL,1701 VINE ST,80.69B,NO PARKING,73.0,6.462770e+06,1.859525e+06,05,15 12:00:00 AM

In [86]:
second_split = la_ticket_2017['Split_2'].str.split(' ', n=1, expand = True)
second_split.head()

          0            1
2735704  18  12:00:00 AM
2771883  11  12:00:00 AM
2777524  01  12:00:00 AM
2777558  28  12:00:00 AM
2777651  15  12:00:00 AM

In [87]:
la_ticket_2017["Day"]= second_split[0] 
la_ticket_2017.head()

,Issue Date,Issue time,Meter Id,RP State Plate,Make,Body Style,Color,Location,Violation code,Violation Description,Fine amount,Latitude,Longitude,Month,Split_2,Day
2735704,2017/12/18 12:00:00 AM,2205.0,NaN,CA,HOND,PA,BK,1323 S FLOWER ST,4000A1,NO EVIDENCE OF REG,50.0,6.480729e+06,1.836883e+06,12,18 12:00:00 AM,18
2771883,2017/05/11 12:00:00 AM,800.0,NaN,CA,FRHT,TR,WH,INDIANA/NOAKES,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,05,11 12:00:00 AM,11
2777524,2017/03/01 12:00:00 AM,104.0,NaN,OR,TOYT,PA,BL,1822 WINONA BLVD,80.56E4+,RED ZONE,93.0,6.470239e+06,1.860397e+06,03,01 12:00:00 AM,01
2777558,2017/03/28 12:00:00 AM,1050.0,NaN,CA,HOND,PA,BK,710 EL CENTRO AV,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,03,28 12:00:00 AM,28
2777651,2017/05/15 12:00:00 AM,134.0,NaN,CA,LEXS,PA,BL,1701 VINE ST,80.69B,NO PARKING,73.0,6.462770e+06,1.859525e+06,05,15 12:00:00 AM,15

### Drop Original Issue Date

In [92]:
# la_ticket_2017 = la_ticket_2017.drop('Issue Date', axis = 1)
# la_ticket_2017 = la_ticket_2017.drop('Split_2', axis = 1)
la_ticket_2017

,Issue time,Meter Id,RP State Plate,Make,Body Style,Color,Location,Violation code,Violation Description,Fine amount,Latitude,Longitude,Month,Day
2735704,2205.0,NaN,CA,HOND,PA,BK,1323 S FLOWER ST,4000A1,NO EVIDENCE OF REG,50.0,6.480729e+06,1.836883e+06,12,18
2771883,800.0,NaN,CA,FRHT,TR,WH,INDIANA/NOAKES,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,05,11
2777524,104.0,NaN,OR,TOYT,PA,BL,1822 WINONA BLVD,80.56E4+,RED ZONE,93.0,6.470239e+06,1.860397e+06,03,01
2777558,1050.0,NaN,CA,HOND,PA,BK,710 EL CENTRO AV,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,03,28
2777651,134.0,NaN,CA,LEXS,PA,BL,1701 VINE ST,80.69B,NO PARKING,73.0,6.462770e+06,1.859525e+06,05,15
2778723,135.0,NaN,CO,TOYT,PA,BL,1701 VINE ST,80.69B,NO PARKING,73.0,6.462770e+06,1.859525e+06,05,15
2779495,1157.0,YO6,CA,BMW,PA,BK,5135 YORK BL,88.13B+,METER EXP.,63.0,6.499917e+06,1.866453e+06,05,22
2779619,100.0,NaN,CA,DODG,PA,GY,4051 NAOMI AVE,80.56E4+,RED ZONE,93.0,6.484604e+06,1.826188e+06,09,30
2791828,2015.0,NaN,CA,TOYO,SU,GY,11126 ORCAS AVE,6344K2,NO PK BET 1-3AM,68.0,6.450282e+06,1.921062e+06,06,10
2795552,1150.0,NaN,CA,BUIC,PA,BL,CULVER DR/INGLEWOOD,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,05,21
2798047,1740.0,NaN,CA,SCIO,PA,BK,METTLER S/O VERNON,013,22500H,68.0,9.999900e+04,9.999900e+04,07,13
2798961,1040.0,NaN,CA,VOLK,PA,BK,ADAMS/GRAMERCY,099,5204,25.0,9.999900e+04,9.999900e+04,06,14
2801744,618.0,NaN,CA,FORD,PA,BR,7328 S MAIN ST,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04,06,25
2803662,1530.0,NaN,CA,GMC,SU,TA,FEDORA/SAN MARINO,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,06,23
2817033,1320.0,NaN,CA,HOND,PA,NaN,380 WORLD WAY L/L,8936,RED CURB,93.0,6.439920e+06,1.802687e+06,05,15
2817916,916.0,NaN,CA,HOND,PA,GY,8417 SO SAN PEDRO ST,8061,STNDNG IN ALLEY,68.0,9.999900e+04,9.999900e+04,08,08
2827647,115.0,NaN,CA,HOND,PA,GY,7502 WILLIS AVENUE,22500E,BLOCKING DRIVEWAY,68.0,6.424012e+06,1.897916e+06,01,03
2827648,126.0,NaN,CA,FORD,VN,WT,14957 FRIAR STREET,5204A-,DISPLAY OF TABS,25.0,6.422948e+06,1.890266e+06,01,03
2827649,132.0,NaN,CA,HOND,PA,BK,14634 SYLVAN ST,22514,FIRE HYDRANT,68.0,6.425072e+06,1.889888e+06,01,03
2827650,44.0,NaN,CA,HOND,PA,RD,1487 28TH ST W,22500E,BLOCKING DRIVEWAY,68.0,6.472759e+06,1.833276e+06,01,03
2828003,134.0,NaN,CA,BMW,PA,RD,501 WEST 127TH STREET,80.56E4+,RED ZONE,NaN,6.475850e+06,1.792522e+06,01,10
2828204,102.0,NaN,CA,NISS,PA,GY,9500 BROADWAY,80.56E4+,RED ZONE,93.0,6.477307e+06,1.804335e+06,01,19
2828265,9.0,NaN,TX,CHEV,PA,BK,950 NORTH GOWER STREET,80.69B,NO PARKING,73.0,6.464091e+06,1.855431e+06,01,20
2828402,2358.0,NaN,CA,HOND,PA,BK,650 TOWNE AVENUE,80.69B,NO PARKING,73.0,6.487630e+06,1.837169e+06,01,22
2828778,132.0,47,CA,CHEV,PA,BK,425 GARDNER ST N,80.58L,PREFERENTIAL PARKING,68.0,6.454707e+06,1.851218e+06,01,31
2828779,133.0,NaN,CA,CHEV,PA,BK,425 GARDNER ST N,5204A-,DISPLAY OF TABS,25.0,6.454707e+06,1.851218e+06,01,31
2828780,134.0,47,CA,CHEV,PA,BK,429 GARDNER ST N,80.58L,PREFERENTIAL PARKING,68.0,6.454707e+06,1.851248e+06,01,31
2828781,136.0,47,CA,STRN,PA,GO,430 GARDNER ST N,80.58L,PREFERENTIAL PARKING,68.0,6.454707e+06,1.851262e+06,01,31
2828782,141.0,132,CA,SUBA,PA,MR,340 SIERRA BONITA AVE N,80.58L,PREFERENTIAL PARKING,68.0,6.454391e+06,1.850589e+06,01,31
2829305,140.0,NaN,CA,HOND,PA,WT,5300 12TH ST W,80.56E4+,RED ZONE,93.0,6.456178e+06,1.842030e+06,02,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764430,1240.0,NaN,CA,HOND,PA,BK,13803 VANOWEN,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,10,12
6783940,418.0,NaN,CA,SMAR,PA,WH,5867 S CENTRAL,225078A,HANDICAP/NO DP ID,363.0,9.999900e+04,9.999900e+04,12,18
6793226,1440.0,NaN,CA,KIA,PA,WH,N VENICE/OCEAN FRONT,000,NaN,NaN,9.999900e+04,9.999900e+04,04,18
6803476,2040.0,NaN,CA,HOND,PA,BK,115TH-WILMINGTON,8056E4,RED ZONE,93.0,9.999900e+04,9.999900e+04,01,13
6827881,940.0,NaN,CA,NISS,PA,BK,1860 S ORANGE GROVE,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,05,20
6836072,1850.0,NaN,CA,FORD,PA,RE,DOCKWEILER PARKING,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,05,28
6846193,725.0,NaN,CA,TOYO,SU,BU,ROSE AVE-3RD AVE,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,07,23
6856146,2125.0,NaN,CA,VW,PA,WH,6615 PACIFIC AVE,8603,PK IN PROH AREA,68.0,6.424732e+06,1.808178e+06,05,07
6858127,1020.0,NaN,CA,JEEP,PA,WH,900 S HARVARD BL,5204A,EXPIRED TAGS,25.0,6.469539e+06,1.842856e+06,06,20
6872418,1802.0,NaN,CA,NaN,PA,GY,3720 STEPHEN M WHITE,8603,PK IN PROH AREA,68.0,6.474665e+06,1.717173e+06,05,12
6874128,817.0,NaN,CA,GIVI,PA,WH,1024 OXFORD,8069BS,NO PARK/STREET CLEAN,73.0,9.999900e+04,9.999900e+04,06,08
6876709,1005.0,NaN,CA,DODG,PA,SI,S/CURB OF EXPOSITION,8069BS,NO PARK/STREET CLEAN,73.0,9.999900e+04,9.999900e+04,07,26
6879675,2350.0,NaN,CA,NaN,VN,GY,L/L 100 WORLD WAY,8939,WHITE CURB,58.0,6.440041e+06,1.802686e+06,07,17
6885583,1810.0,NaN,CA,TOYO,PA,TA,763 CALIBURN AVE,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,06,11
6888525,1206.0,NaN,CA,KIA,PA,WH,W OBSERVATORY/WESTER,8049,WRG SD/NOT PRL,63.0,9.999900e+04,9.999900e+04,10,06
6894556,710.0,NaN,CA,CHEV,TR,NaN,30TH/MAIN,8056E4,RED ZONE,93.0,9.999900e+04,9.999900e+04,07,08
6898044,840.0,NaN,CA,CHEV,PA,GR,W 227TH ST E/O WESTE,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,03,15
6922093,1523.0,OF132,CA,VOLK,PA,BK,900 FAIRFAX AVE,8813B,METER EXPIRED,63.0,6.451762e+06,1.844446e+06,09,14
6927503,940.0,NaN,CA,FORD,TR,BU,441 W 2ND ST,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04,06,26
6972988,1133.0,NaN,CA,NISS,PA,WH,11770 FOOTHILL BLVD,8069B,NO PARKING,73.0,6.443161e+06,1.921958e+06,08,12
6979891,805.0,NaN,CA,HOND,PA,BL,7610 WOODLEY AVE,89391C,EXCEED TIME LMT,58.0,6.415432e+06,1.898663e+06,08,06
7024755,1005.0,NaN,CA,CHEV,TR,WH,ELDEN AVE/11TH ST,8056E4,RED ZONE,93.0,9.999900e+04,9.999900e+04,09,03
7026842,1302.0,NaN,CA,HOND,PA,WH,5663 VIRGINIA AVE,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,08,08
7052208,653.0,NaN,CA,BMW,PA,WH,1625 MICHAEL LN,099,5204,25.0,9.999900e+04,9.999900e+04,09,24
7052213,557.0,NaN,CA,TOYO,PA,WT,1200 HUNTLEY DR,8056E4,RED ZONE,93.0,9.999900e+04,9.999900e+04,09,28
7094534,2008.0,NaN,NV,CHRY,PA,GY,2800 EAST OBSERVATOR,8056E4,RED ZONE,93.0,9.999900e+04,9.999900e+04,04,17
7133441,150.0,NaN,CA,ACUR,PA,GY,BURNS E/O VIRGIL,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,11,05
7171053,1637.0,NaN,CA,HOND,PA,BK,2167 E 102ND ST,80714,PRIVATE PROPERTY,68.0,6.490781e+06,1.802058e+06,10,15
7171388,735.0,NaN,CA,CHEV,PA,BL,6701 DE SOTO AVE,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,04,16
7171390,1635.0,NaN,CA,TOYO,PA,GY,101 WORLD WAY,225078A,HANDICAP/NO DP ID,363.0,6.439738e+06,1.802687e+06,03,05

### Write Reduced 2017 Dataset

In [96]:
la_ticket_2017.to_csv('la_ticket_2017.csv')

In [97]:
# check size again
os.path.getsize('la_ticket_2017.csv') / (1*10**9)
# still too big, must be < 100 mb

0.260689419

### Divide Dataset into 3 parts for github upload

In [140]:
seq_1 = ['01','02','03','04']
seq_2 = ['05','06','07','08']
seq_3 = ['09','10','11','12']

In [146]:
index_1 = la_ticket_2017['Month'].isin(seq_1)
index_2 = la_ticket_2017['Month'].isin(seq_2)
index_3 = la_ticket_2017['Month'].isin(seq_3)

In [149]:
la_ticket_2017_1 = la_ticket_2017[index_1]
la_ticket_2017_2 = la_ticket_2017[index_2]
la_ticket_2017_3 = la_ticket_2017[index_3]

In [150]:
la_ticket_2017_1.to_csv('la_ticket_2017_1.csv')
la_ticket_2017_2.to_csv('la_ticket_2017_2.csv')
la_ticket_2017_3.to_csv('la_ticket_2017_3.csv')

In [151]:
os.path.getsize('la_ticket_2017_1.csv') / (1*10**9)

0.087559057

In [152]:
os.path.getsize('la_ticket_2017_2.csv') / (1*10**9)

0.091274036

In [153]:
os.path.getsize('la_ticket_2017_3.csv') / (1*10**9)

0.081856616

### Trim Complete